import Header from "./Header/Header";
import Signin from "./Signin/Signin";
import Signup from "./Signup/Signup";
import Home from "./Home/Home";
import Profile from "./Profile/Profile";
import SearchResult from "./SearchResult/SearchResult";
import CreatePost from "./CreatePost/CreatePost";
import PostDetailsh from "./PostDetails/PostDetailsh";
import PostDetailsp from "./PostDetails/PostDetailsp";
import PostDetailsE from "./PostDetails/PostDetailsE";
import OtherProfile from "./othersProfile/OtherProfile";
import Followers from "./FollowList/Followers";
import Following from "./FollowList/Following";
import Explore from "./Explore/Explore";
export { Header, Signin, Signup, Home, Profile, Followers, Following, CreatePost, PostDetailsh, PostDetailsp, PostDetailsE, Explore, SearchResult, OtherProfile };